#!/usr/bin/env python3
"""Render the system-level comparison of Max with the other tools.

    python3 scans/max-gaps/build_system_differences.py

Reads one system model per tool, each a JSON list written against
SYSTEM_DIMENSIONS.md:

    scans/max-gaps/max_system_model.json          Max itself
    scans/<tool>/<tool>_system_model.json         each other tool

and the hand-written comparison in `system_differences_notes.json`:

    {"overview": ["one finding per line", ...],
     "dimensions": {"1": {"difference": "...", "advice": "..."}, ...}}

and writes `system_differences.md`. Edit the JSON files, not the Markdown.
A missing model file is reported, not skipped silently.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
SCANS = HERE.parent
OUT = HERE / "system_differences.md"
NOTES = HERE / "system_differences_notes.json"

MAX_MODEL = HERE / "max_system_model.json"
TOOLS = [  # (label, path)
    ("TouchDesigner", SCANS / "touchdesigner" / "touchdesigner_system_model.json"),
    ("MadMapper", SCANS / "madmapper" / "madmapper_system_model.json"),
    ("Isadora", SCANS / "isadora" / "isadora_system_model.json"),
    ("cables.gl", SCANS / "cables-gl" / "cables_gl_system_model.json"),
    ("Pd / plugdata", SCANS / "plugdata" / "plugdata_system_model.json"),
]


def load(path, problems):
    if not path.exists():
        problems.append(f"missing: {path.relative_to(SCANS)}")
        return {}
    try:
        items = json.loads(path.read_text(encoding="utf-8"))
    except ValueError as err:
        problems.append(f"not valid JSON: {path.relative_to(SCANS)} ({err})")
        return {}
    if not isinstance(items, list):
        problems.append(f"{path.relative_to(SCANS)} holds a {type(items).__name__}, not a list")
        return {}
    return {int(i["id"]): i for i in items if isinstance(i, dict) and "id" in i}


def one_line(text):
    return " ".join(str(text).split())


def main():
    problems = []
    max_model = load(MAX_MODEL, problems)
    models = [(label, load(path, problems)) for label, path in TOOLS]
    notes = json.loads(NOTES.read_text(encoding="utf-8")) if NOTES.exists() else {}
    dim_notes = notes.get("dimensions", {})

    # Ids 1-20 are the shared list. Ids above 20 were added by each scan on its
    # own, so the same number means different things in different files.
    ids = list(range(1, 21))
    names = {}
    for source in [max_model] + [m for _, m in models]:
        for i, item in source.items():
            names.setdefault(i, item.get("dimension", f"Dimension {i}"))

    out = [
        "# How Max's General Approach Differs From Other Tools",
        "",
        "Generated by `build_system_differences.py`. Edit the JSON files it names, not this file.",
        "",
        "Each tool's column was written from that tool's own documentation; Max's from Max's",
        "userguide and refpages. The comparison and advice lines are written by hand in",
        "`system_differences_notes.json`. Nothing here was run in any of the tools.",
        "",
    ]
    if notes.get("overview"):
        out += ["## Main differences in approach", ""]
        out += [f"{n}. {one_line(t)}" for n, t in enumerate(notes["overview"], 1)]
        out.append("")

    out += ["## Dimensions", ""]
    out += [f"- [{i}. {names[i]}](#{i}-{names[i].lower().replace(' ', '-')})" for i in ids]
    out.append("")

    for i in ids:
        out += [f"## {i}. {names[i]}", ""]
        note = dim_notes.get(str(i), {})
        if note.get("difference"):
            out += [f"**The difference:** {one_line(note['difference'])}", ""]
        if note.get("advice"):
            out += [f"**Advice for Max:** {one_line(note['advice'])}", ""]
        m = max_model.get(i)
        if m:
            out += [f"### Max", "", one_line(m.get("summary", ""))]
            if m.get("strengths"):
                out.append(f"- *Does well:* {one_line(m['strengths'])}")
            if m.get("costs"):
                out.append(f"- *Makes hard:* {one_line(m['costs'])}")
            out += [f"- *Confidence:* {m.get('confidence', '?')}", ""]
        for label, model in models:
            t = model.get(i)
            if not t:
                continue
            out += [f"### {label}", "", one_line(t.get("summary", ""))]
            if t.get("what_a_max_user_would_notice"):
                out.append(f"- *Coming from Max:* {one_line(t['what_a_max_user_would_notice'])}")
            out += [f"- *Confidence:* {t.get('confidence', '?')}", ""]

    out += ["## Dimensions only one tool named", "",
            "Each scan could add system-level dimensions the shared list lacks. These are",
            "per tool: the same number means different things in different files.", ""]
    extra_notes = notes.get("extras", {})
    for label, model in [("Max", max_model)] + models:
        extras = [model[i] for i in sorted(model) if i > 20]
        if not extras:
            continue
        out += [f"### {label}", ""]
        for t in extras:
            out.append(f"- **{t.get('dimension', '?')}.** {one_line(t.get('summary', ''))}")
            key = f"{label}: {t.get('dimension', '')}"
            if extra_notes.get(key):
                out.append(f"  - *For Max:* {one_line(extra_notes[key])}")
        out.append("")

    out += ["## Sources", "",
            "Each item in the JSON files lists its own sources and detail bullets."]
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(ids)} dimensions")
    for p in problems:
        print("  problem:", p)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
