#!/usr/bin/env python3
"""Generated copies are rebuilt whenever their sources change.
Run: python3 tests/test_generated_copies_current.py

Two copies drifted from their sources unnoticed (found 2026-09-16):
claude-project/SPEC_REFERENCE.md had not been rebuilt since 09-08, and
c2m-explain/UPSTREAM-SKILL.md, then maintained by hand, still advised the
extract → edit → convert workflow the repo had retired. Both now come from a
builder with a --check mode, and this test runs it, so a source edit without
a rebuild fails here instead of shipping stale.
"""
import subprocess
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO / "tools"))
import build_upstream_skills  # noqa: E402


def _check(script):
    return subprocess.run([sys.executable, str(_REPO / "tools" / script), "--check"],
                          capture_output=True, text=True)


def test_claude_project_is_current():
    r = _check("build_claude_project.py")
    assert r.returncode == 0, r.stdout + r.stderr


def test_upstream_skills_are_current():
    r = _check("build_upstream_skills.py")
    assert r.returncode == 0, r.stdout + r.stderr


def test_upstream_build_adapts_the_in_repo_skill():
    src = _REPO / ".claude" / "skills" / "c2m-explain" / "SKILL.md"
    out = build_upstream_skills.build(src)
    assert out.startswith("---\nname: c2m-explain\n")
    assert "user-invocable: true" in out and "argument-hint:" not in out
    assert "$ARGUMENTS" not in out
    assert "UPSTREAM-SKILL.md` — the upstream-distribution copy" not in out
    assert "generated by `tools/build_upstream_skills.py`" in out


if __name__ == "__main__":
    for name, fn in list(globals().items()):
        if name.startswith("test_"):
            fn(); print("  PASS ", name)
