#!/usr/bin/env python3
"""
build_upstream_skills.py — regenerate `<tool>/UPSTREAM-SKILL.md` from the in-repo skill.

An UPSTREAM-SKILL.md is the copy of a skill meant for a separate distribution
repo. It was maintained by hand beside `.claude/skills/<name>/SKILL.md` and
drifted: by 2026-09-16 the c2m-explain copy still told readers to modify a
patch with extract → edit → convert, which the repo's rules had since
forbidden. This script builds the upstream copy from the in-repo skill so the
two cannot disagree. Edit `.claude/skills/<name>/SKILL.md`, then run this.

What changes on the way out:
  - frontmatter: `argument-hint` (a slash-command feature) becomes `user-invocable: true`
  - `$ARGUMENTS` becomes `<patch.maxpat>`, since there is no slash command outside this repo
  - the in-repo line pointing at the upstream copy is dropped
  - a banner under the title says which file is authoritative

Only skills listed in PAIRS are built. c2m-themes/UPSTREAM-SKILL.md has no
in-repo twin, so it is not one of them.

Usage:
    python3 tools/build_upstream_skills.py           # write the upstream copies
    python3 tools/build_upstream_skills.py --check   # exit 1 if any would change
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PAIRS = {
    REPO / ".claude" / "skills" / "c2m-explain" / "SKILL.md": REPO / "c2m-explain" / "UPSTREAM-SKILL.md",
}

BANNER = ("> **This is the upstream/distribution copy of the manifest, generated by "
          "`tools/build_upstream_skills.py`.** The authoritative copy is `{src}`; edit that one "
          "and re-run the script.\n")


def build(src: Path) -> str:
    text = src.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        raise SystemExit(f"{src}: no frontmatter")
    front = [l for l in m.group(1).splitlines() if not l.startswith("argument-hint:")]
    front.append("user-invocable: true")
    body = text[m.end():]
    body = body.replace('"$ARGUMENTS"', "<patch.maxpat>").replace("`$ARGUMENTS`", "a `.maxpat` path")
    body = "\n".join(l for l in body.splitlines() if "UPSTREAM-SKILL.md" not in l) + "\n"
    title = re.search(r"^# .*\n", body, re.M)
    rel = src.relative_to(REPO)
    if title:
        body = body[:title.end()] + "\n" + BANNER.format(src=rel) + body[title.end():]
    return "---\n" + "\n".join(front) + "\n---\n" + body


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if any upstream copy is stale")
    args = ap.parse_args()
    stale = []
    for src, dst in PAIRS.items():
        want = build(src)
        have = dst.read_text(encoding="utf-8") if dst.exists() else None
        if want == have:
            print(f"{dst.relative_to(REPO)} is up to date")
            continue
        stale.append(dst)
        if args.check:
            print(f"{dst.relative_to(REPO)} is STALE — run tools/build_upstream_skills.py")
        else:
            dst.write_text(want, encoding="utf-8")
            print(f"wrote {dst.relative_to(REPO)}")
    return 1 if (args.check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())
